import type { ElementPaletteItem } from '../../components/idcard/studio/studioTypes';

export const PRINT_SAFE_FONTS = [
  { value: "'Times New Roman', serif", label: 'Times New Roman (Standard)' },
  { value: "'Inter', sans-serif", label: 'Inter (Modern Sans)' },
  { value: "'Roboto', sans-serif", label: 'Roboto (Clean Sans)' },
  { value: "'Arial', sans-serif", label: 'Arial (Universal Sans)' },
  { value: "'Georgia', serif", label: 'Georgia (Editorial Serif)' },
  { value: "'Poppins', sans-serif", label: 'Poppins (Geometric Sans)' },
  { value: "'Montserrat', sans-serif", label: 'Montserrat (Display Sans)' },
  { value: "'Courier New', monospace", label: 'Courier New (Monospace ID)' },
];

export const ELEMENT_PALETTE: ElementPaletteItem[] = [
  // ── Student Data ──────────────────────────────────────────
  {
    key: 'student_name',
    label: 'Student Name',
    category: 'student_data',
    icon: 'User',
    description: 'Full name of the student',
    defaultWidth: 46.0,
    defaultHeight: 4.8,
    defaultFontSize: 8.5,
    defaultFontWeight: 'bold',
    defaultColor: '#1B2A4A',
    source: 'dynamic',
    dataType: 'text',
  },
  {
    key: 'student_id',
    label: 'Student ID / Adm No',
    category: 'student_data',
    icon: 'BadgeCheck',
    description: 'Unique student identifier or admission number',
    defaultWidth: 38.0,
    defaultHeight: 3.5,
    defaultFontSize: 6.5,
    defaultFontWeight: 'bold',
    defaultColor: '#1B2A4A',
    defaultLabelPrefix: 'ID NO: ',
    source: 'dynamic',
    dataType: 'text',
  },
  {
    key: 'class',
    label: 'Class / Grade',
    category: 'student_data',
    icon: 'GraduationCap',
    description: 'Class or standard of the student',
    defaultWidth: 26.0,
    defaultHeight: 3.5,
    defaultFontSize: 6.5,
    defaultFontWeight: 'bold',
    defaultColor: '#1B2A4A',
    defaultLabelPrefix: 'CLASS: ',
    source: 'dynamic',
    dataType: 'text',
  },
  {
    key: 'section',
    label: 'Section',
    category: 'student_data',
    icon: 'Grid',
    description: 'Section of the class',
    defaultWidth: 18.0,
    defaultHeight: 3.5,
    defaultFontSize: 6.5,
    defaultFontWeight: 'bold',
    defaultColor: '#1B2A4A',
    defaultLabelPrefix: 'SEC: ',
    source: 'dynamic',
    dataType: 'text',
  },
  {
    key: 'roll_number',
    label: 'Roll Number',
    category: 'student_data',
    icon: 'Hash',
    description: 'Class roll number',
    defaultWidth: 20.0,
    defaultHeight: 3.5,
    defaultFontSize: 6.5,
    defaultFontWeight: 'bold',
    defaultColor: '#1B2A4A',
    defaultLabelPrefix: 'ROLL NO: ',
    source: 'dynamic',
    dataType: 'text',
  },
  {
    key: 'father_name',
    label: "Father's Name",
    category: 'student_data',
    icon: 'Users',
    description: "Father's full name",
    defaultWidth: 46.0,
    defaultHeight: 3.5,
    defaultFontSize: 6.5,
    defaultFontWeight: 'bold',
    defaultColor: '#1B2A4A',
    defaultLabelPrefix: "FATHER'S NAME: ",
    source: 'dynamic',
    dataType: 'text',
  },
  {
    key: 'mother_name',
    label: "Mother's Name",
    category: 'student_data',
    icon: 'Heart',
    description: "Mother's full name",
    defaultWidth: 46.0,
    defaultHeight: 3.5,
    defaultFontSize: 6.5,
    defaultFontWeight: 'bold',
    defaultColor: '#1B2A4A',
    defaultLabelPrefix: "MOTHER'S NAME: ",
    source: 'dynamic',
    dataType: 'text',
  },
  {
    key: 'date_of_birth',
    label: 'Date of Birth',
    category: 'student_data',
    icon: 'Calendar',
    description: 'Student date of birth',
    defaultWidth: 38.0,
    defaultHeight: 3.5,
    defaultFontSize: 6.5,
    defaultFontWeight: 'bold',
    defaultColor: '#1B2A4A',
    defaultLabelPrefix: 'D.O.B: ',
    source: 'dynamic',
    dataType: 'date',
  },
  {
    key: 'blood_group',
    label: 'Blood Group',
    category: 'student_data',
    icon: 'Droplet',
    description: 'Emergency blood group indicator',
    defaultWidth: 28.0,
    defaultHeight: 3.5,
    defaultFontSize: 6.5,
    defaultFontWeight: 'bold',
    defaultColor: '#1B2A4A',
    defaultLabelPrefix: 'BLOOD GROUP: ',
    source: 'dynamic',
    dataType: 'text',
  },
  {
    key: 'phone',
    label: 'Contact Number',
    category: 'student_data',
    icon: 'Phone',
    description: 'Primary contact phone number',
    defaultWidth: 46.0,
    defaultHeight: 3.5,
    defaultFontSize: 6.5,
    defaultFontWeight: 'bold',
    defaultColor: '#1B2A4A',
    defaultLabelPrefix: 'MOB: ',
    source: 'dynamic',
    dataType: 'text',
  },
  {
    key: 'emergency_no',
    label: 'Emergency Number',
    category: 'student_data',
    icon: 'ShieldAlert',
    description: 'Emergency contact telephone',
    defaultWidth: 46.0,
    defaultHeight: 3.5,
    defaultFontSize: 6.5,
    defaultFontWeight: 'bold',
    defaultColor: '#1B2A4A',
    defaultLabelPrefix: 'EMERGENCY: ',
    source: 'dynamic',
    dataType: 'text',
  },
  {
    key: 'address',
    label: 'Address',
    category: 'student_data',
    icon: 'MapPin',
    description: 'Residential / communication address',
    defaultWidth: 46.0,
    defaultHeight: 7.0,
    defaultFontSize: 5.5,
    defaultFontWeight: 'normal',
    defaultColor: '#1B2A4A',
    defaultLabelPrefix: 'ADDRESS: ',
    source: 'dynamic',
    dataType: 'text',
  },
  {
    key: 'valid_till',
    label: 'Valid Till / Expiry',
    category: 'student_data',
    icon: 'Clock',
    description: 'Card validity expiration period',
    defaultWidth: 32.0,
    defaultHeight: 3.2,
    defaultFontSize: 5.5,
    defaultFontWeight: 'bold',
    defaultColor: '#1B2A4A',
    defaultLabelPrefix: 'VALID UPTO: ',
    defaultCustomText: '2026-2027',
    source: 'static',
    dataType: 'text',
  },

  // ── Images & Assets ───────────────────────────────────────
  {
    key: 'student_photo',
    label: 'Student Photo',
    category: 'images',
    icon: 'Camera',
    description: 'Student portrait photograph placeholder',
    defaultWidth: 20.0,
    defaultHeight: 25.0,
    isImage: true,
    source: 'dynamic',
    dataType: 'photo',
  },
  {
    key: 'school_logo',
    label: 'School / Institution Logo',
    category: 'images',
    icon: 'Building2',
    description: 'Official institutional crest or logo',
    defaultWidth: 14.0,
    defaultHeight: 14.0,
    isImage: true,
    source: 'system',
    dataType: 'photo',
  },

  // ── Generated Codes ───────────────────────────────────────
  {
    key: 'qr_code',
    label: 'Verification QR Code',
    category: 'generated',
    icon: 'QrCode',
    description: 'Digital identity verification QR link',
    defaultWidth: 16.0,
    defaultHeight: 16.0,
    isImage: true,
    source: 'system',
  },
  {
    key: 'barcode',
    label: 'Barcode (Code 128)',
    category: 'generated',
    icon: 'Barcode',
    description: 'Scannable library & turnstile barcode',
    defaultWidth: 36.0,
    defaultHeight: 7.5,
    isImage: true,
    source: 'system',
  },

  // ── Design & Static Text ──────────────────────────────────
  {
    key: 'school_name',
    label: 'School Name Header',
    category: 'design',
    icon: 'Building',
    description: 'Prominent institution name banner',
    defaultWidth: 46.0,
    defaultHeight: 6.0,
    defaultFontSize: 11.0,
    defaultFontWeight: '800',
    defaultColor: '#FFFFFF',
    defaultCustomText: 'SPARKNEST ACADEMY',
    source: 'static',
    dataType: 'text',
  },
  {
    key: 'school_subtitle',
    label: 'School Subtitle / Tagline',
    category: 'design',
    icon: 'Type',
    description: 'Affiliation, branch or board tagline',
    defaultWidth: 46.0,
    defaultHeight: 3.5,
    defaultFontSize: 5.5,
    defaultFontWeight: 'bold',
    defaultColor: '#FFFFFF',
    defaultCustomText: 'Affiliated to CBSE, New Delhi',
    source: 'static',
    dataType: 'text',
  },
  {
    key: 'custom_text',
    label: 'Custom Static Text',
    category: 'design',
    icon: 'FileText',
    description: 'Arbitrary custom notice, heading, or badge',
    defaultWidth: 30.0,
    defaultHeight: 4.0,
    defaultFontSize: 6.5,
    defaultFontWeight: 'bold',
    defaultColor: '#1B2A4A',
    defaultCustomText: 'STUDENT IDENTITY CARD',
    source: 'static',
    dataType: 'text',
  },
  {
    key: 'terms',
    label: 'Lost Card Return Terms',
    category: 'design',
    icon: 'HelpCircle',
    description: 'Important cardholder return instructions',
    defaultWidth: 46.0,
    defaultHeight: 9.0,
    defaultFontSize: 4.5,
    defaultFontWeight: 'normal',
    defaultColor: '#334155',
    defaultCustomText: 'This card is non-transferable. If found abandoned, please return to the school administration office.',
    source: 'static',
    dataType: 'text',
  },
  {
    key: 'website',
    label: 'Website & Tollfree Line',
    category: 'design',
    icon: 'Globe',
    description: 'Official web portal & helpline contact',
    defaultWidth: 46.0,
    defaultHeight: 3.5,
    defaultFontSize: 5.0,
    defaultFontWeight: 'bold',
    defaultColor: '#1B2A4A',
    defaultCustomText: 'www.schoolwebsite.edu | Helpline: 1800 123 4567',
    source: 'static',
    dataType: 'text',
  },
];
