export type UserRole = 'ADMIN' | 'MANAGER' | 'STAFF';

export type ProjectStatus = 'DRAFT' | 'ACTIVE' | 'COMPLETED' | 'ARCHIVED';

export interface IdCardProject {
  id: string;
  name: string;
  description: string | null;
  academic_year: string;
  status: ProjectStatus;
  template_id: string | null;
  logo_url?: string | null;
  created_by: string;
  created_at: string;
  updated_at: string;
}

export interface PhotoCropState {
  shape: 'circle' | 'rect';
  x: number; // pan offset X in viewport / relative coordinates
  y: number; // pan offset Y in viewport / relative coordinates
  scale: number; // zoom factor (e.g. 1 = 100%, 1.2 = 120%)
  rotation: number; // rotation in degrees (0, 90, 180, 270)
  naturalWidth?: number;
  naturalHeight?: number;
  viewportWidth?: number;
  viewportHeight?: number;
}

export interface IdCardPerson {
  id: string;
  project_id: string;
  student_id: string;
  name: string;
  class: string | null;
  section: string | null;
  roll_number: string | null;
  date_of_birth: string | null;
  blood_group: string | null;
  father_name: string | null;
  mother_name: string | null;
  phone: string | null;
  emergency_number?: string | null;
  address: string | null;
  photo_url: string | null;
  original_photo_url?: string | null;
  photo_crop_state?: PhotoCropState | null;
  custom_fields?: Record<string, any> | null;
  created_at: string;
  updated_at: string;
  [key: string]: any;
}

export type TemplateFieldSource = 'static' | 'dynamic' | 'system';

export type TemplateFieldKey =
  | 'school_logo'
  | 'school_name'
  | 'school_subtitle'
  | 'student_photo'
  | 'student_name'
  | 'student_id'
  | 'class'
  | 'section'
  | 'roll_number'
  | 'date_of_birth'
  | 'blood_group'
  | 'parent_info'
  | 'father_name'
  | 'mother_name'
  | 'phone'
  | 'address'
  | 'academic_year'
  | 'batch'
  | 'designation'
  | 'emergency_no'
  | 'valid_till'
  | 'barcode'
  | 'qr_code'
  | 'terms'
  | 'website'
  | 'custom_text'
  | (string & {});

export interface TemplateField {
  id?: string; // unique identifier for the field instance
  key: TemplateFieldKey;
  label?: string;
  source?: TemplateFieldSource; // 'static' | 'dynamic' | 'system'
  dataType?: 'text' | 'photo' | 'date' | 'select' | 'number';
  value?: string; // static content value (e.g. "ABC Public School")
  isIdentity?: boolean; // true for student_id
  customKey?: string; // stable internal key for custom fields
  x: number; // mm from left (xMm)
  y: number; // mm from top (yMm)
  width: number; // mm (widthMm)
  height: number; // mm (heightMm)
  fontSize?: number; // pt, ignored for image fields
  fontWeight?: 'normal' | 'bold' | '500' | '600' | '700' | '800';
  fontStyle?: 'normal' | 'italic';
  fontFamily?: string;
  color?: string;
  textAlign?: 'left' | 'center' | 'right' | 'justify';
  lineHeight?: number; // unitless multiplier, default 1.2
  letterSpacing?: number; // in mm or pt
  visible: boolean;
  required?: boolean;
  locked?: boolean;
  customText?: string; // used for static content/placeholders
  labelPrefix?: string; // e.g. "BLOOD GROUP:", "FATHER'S NAME:"
  borderRadius?: number; // percentage, 50 = circle
  borderColor?: string;
  borderWidth?: number; // px or mm
  photoShape?: 'rectangle' | 'rounded' | 'circle';
  photoFit?: 'cover' | 'contain' | 'fill';
  overflowStrategy?: 'wrap' | 'scale_down' | 'ellipsis' | 'warning';
  binding?: {
    type: 'student_field' | 'custom_field' | 'static' | 'system';
    fieldId: string;
  };
}

export interface TemplateSideLayout {
  fields: TemplateField[];
  backgroundColor: string;
  backgroundUrl?: string | null;
  backgroundFit?: 'fill' | 'fit' | 'crop';
  backgroundOpacity?: number; // 0 to 100 (%)
  backgroundPosition?: string; // 'center' | 'top' | 'bottom' | 'left' | 'right'
  backgroundScale?: number; // 50 to 200 (%)
  backgroundOffsetX?: number; // -50 to 50 (%)
  backgroundOffsetY?: number; // -50 to 50 (%)
  backgroundBlur?: number; // 0 to 20 (px)
  backgroundBrightness?: number; // 50 to 150 (%)
  backgroundContrast?: number; // 50 to 150 (%)
  headerSvg?: string | null;
  footerSvg?: string | null;
  headerGradientColors?: [string, string] | null;
  footerGradientColors?: [string, string] | null;
}

export type TemplateFieldCategory = 'student_input' | 'student_asset' | 'auto_generated' | 'static';

export interface TemplateFieldSchemaItem {
  key: string;
  label: string;
  type: 'text' | 'photo' | 'date' | 'select' | 'number';
  required: boolean;
  category: TemplateFieldCategory;
  source?: TemplateFieldSource;
  modelKey: keyof IdCardPerson | 'student_photo' | string;
  description?: string;
  side?: 'front' | 'back' | 'both';
  options?: string[];
  placeholder?: string;
  isCustom?: boolean;
  value?: string;
}

export interface TemplateFieldSchema {
  items: TemplateFieldSchemaItem[];
  studentInputFields: TemplateFieldSchemaItem[];
  assetFields: TemplateFieldSchemaItem[];
  autoGeneratedFields: TemplateFieldSchemaItem[];
  staticFields: TemplateFieldSchemaItem[];
}

export interface TemplateLayout {
  fields: TemplateField[]; // Front side fields
  backgroundColor: string;
  backgroundUrl?: string | null; // Front background image
  backgroundFit?: 'fill' | 'fit' | 'crop';
  backgroundOpacity?: number; // 0 to 100 (%)
  backgroundPosition?: string; // 'center' | 'top' | 'bottom' | 'left' | 'right'
  backgroundScale?: number; // 50 to 200 (%)
  backgroundOffsetX?: number; // -50 to 50 (%)
  backgroundOffsetY?: number; // -50 to 50 (%)
  backgroundBlur?: number; // 0 to 20 (px)
  backgroundBrightness?: number; // 50 to 150 (%)
  backgroundContrast?: number; // 50 to 150 (%)
  schoolLogoUrl?: string | null; // School / Organization logo URL
  headerSvg?: string | null; // SVG markup for header decoration
  footerSvg?: string | null; // SVG markup for footer decoration
  headerGradientColors?: [string, string] | null; // [primary, accent]
  footerGradientColors?: [string, string] | null; // [primary, accent]
  presetId?: string; // identifier for the base preset
  orientation?: 'portrait' | 'landscape';
  cardType?: 'student' | 'staff' | 'employee' | 'faculty' | 'visitor' | 'event' | 'custom';
  widthMm?: number;
  heightMm?: number;
  isDoubleSided?: boolean;
  templateType?: 'single' | 'double';
  textCase?: 'uppercase' | 'normal';
  back?: TemplateSideLayout; // Back side layout
  fieldSchema?: TemplateFieldSchemaItem[]; // Extracted dynamic field schema
  [key: string]: any;
}

export interface IdCardTemplate {
  id: string;
  project_id: string | null;
  name: string;
  layout: TemplateLayout;
  card_width_mm: number;
  card_height_mm: number;
  orientation?: 'portrait' | 'landscape';
  card_type?: string;
  background_url: string | null;
  logo_url?: string | null;
  version?: number;
  created_by: string;
  created_at: string;
  updated_at: string;
}

export type GenerationStatus = 'PENDING' | 'SUCCESS' | 'FAILED';

export type IdCardStatus =
  | 'NOT_READY'              // Incomplete required student info / photo based on active template
  | 'READY_TO_GENERATE'     // Fully validated, complete, ready for card generation
  | 'READY_TO_PRINT'        // Card successfully generated, queued / ready for physical printing
  | 'PRINTED'               // Successfully printed
  | 'PRINT_FAILED'          // Print operation failed or was interrupted -> eligible for retry
  | 'REPRINT_REQUIRED'      // Damaged/lost/misprint or admin requested reprint with reason
  | 'OUTDATED';             // Student data or photo was modified after last generation/print

export type ReprintReason =
  | 'DAMAGED_CARD'
  | 'INCORRECT_PRINT'
  | 'LOST_CARD'
  | 'INFO_CHANGED'
  | 'PHOTO_CHANGED'
  | 'ADMIN_REQUEST';

export interface PrintHistoryEntry {
  id: string;
  project_id: string;
  person_id: string;
  student_id: string;
  generation_id?: string;
  template_id?: string;
  template_name?: string;
  session_id?: string;
  print_number: number;
  status: 'SUCCESS' | 'FAILED' | 'REPRINT_REQUESTED';
  reprint_reason?: ReprintReason | string;
  notes?: string;
  printed_by?: string;
  timestamp: string;
}

export interface StudentIdCardStatusInfo {
  status: IdCardStatus;
  ready: boolean;
  missingFields: string[];
  missingFieldKeys: string[];
  lastGeneration?: IdCardGeneration | null;
  printCount: number;
  firstPrintedAt?: string | null;
  lastPrintedAt?: string | null;
  lastFailedAt?: string | null;
  reprintReason?: string | null;
  isOutdated: boolean;
  outdatedReason?: string | null;
  canGenerate: boolean;
  canPrint: boolean;
}

export interface IdCardGeneration {
  id: string;
  project_id: string;
  person_id: string;
  template_id: string;
  template_version?: number | null;
  template_layout_snapshot?: TemplateLayout | null;
  status: GenerationStatus;
  file_url: string | null;
  error_message: string | null;
  generated_by: string;
  created_at: string;
  printed_at: string | null;
}

export type AppErrorCode =
  | 'AUTH_REQUIRED'
  | 'ACCESS_DENIED'
  | 'VALIDATION_ERROR'
  | 'NOT_FOUND'
  | 'DATABASE_ERROR'
  | 'STORAGE_ERROR'
  | 'NETWORK_ERROR'
  | 'UNKNOWN_ERROR';

export class AppError extends Error {
  code: AppErrorCode;
  cause?: unknown;

  constructor(code: AppErrorCode, message: string, cause?: unknown) {
    super(message);
    this.code = code;
    this.cause = cause;
  }
}

export interface CsvValidationRow {
  rowNumber: number;
  data: Partial<IdCardPerson>;
  errors: string[];
  valid: boolean;
}

export interface PaginatedResult<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
}

export type { CanonicalStudent, CanonicalFieldKey, CanonicalFieldDefinition } from './dataBindingRegistry';
