export type UserRole = 'ADMIN' | 'MANAGER' | 'STAFF';

export type ProjectStatus = 'DRAFT' | 'ACTIVE' | 'COMPLETED' | 'ARCHIVED';

export interface IdCardProject {
  id: string;
  name: string;
  description: string | null;
  academic_year: string;
  status: ProjectStatus;
  template_id: string | null;
  logo_url?: string | null;
  created_by: string;
  created_at: string;
  updated_at: string;
}

export interface IdCardPerson {
  id: string;
  project_id: string;
  student_id: string;
  name: string;
  class: string | null;
  section: string | null;
  roll_number: string | null;
  date_of_birth: string | null;
  blood_group: string | null;
  father_name: string | null;
  mother_name: string | null;
  phone: string | null;
  address: string | null;
  photo_url: string | null;
  created_at: string;
  updated_at: string;
}

export type TemplateFieldKey =
  | 'school_logo'
  | 'school_name'
  | 'school_subtitle'
  | 'student_photo'
  | 'student_name'
  | 'student_id'
  | 'class'
  | 'section'
  | 'roll_number'
  | 'date_of_birth'
  | 'blood_group'
  | 'parent_info'
  | 'father_name'
  | 'mother_name'
  | 'phone'
  | 'address'
  | 'academic_year'
  | 'batch'
  | 'designation'
  | 'emergency_no'
  | 'valid_till'
  | 'barcode'
  | 'qr_code'
  | 'terms'
  | 'website'
  | 'custom_text';

export interface TemplateField {
  id?: string; // unique identifier for the field instance
  key: TemplateFieldKey;
  label?: string;
  x: number; // mm from left (xMm)
  y: number; // mm from top (yMm)
  width: number; // mm (widthMm)
  height: number; // mm (heightMm)
  fontSize?: number; // pt, ignored for image fields
  fontWeight?: 'normal' | 'bold' | '500' | '600' | '700' | '800';
  fontStyle?: 'normal' | 'italic';
  fontFamily?: string;
  color?: string;
  textAlign?: 'left' | 'center' | 'right' | 'justify';
  lineHeight?: number; // unitless multiplier, default 1.2
  letterSpacing?: number; // in mm or pt
  visible: boolean;
  required?: boolean;
  locked?: boolean;
  customText?: string; // used for custom_text, designation, emergency_no, valid_till, terms, website
  labelPrefix?: string; // e.g. "BLOOD GROUP:", "FATHER'S NAME:"
  borderRadius?: number; // percentage, 50 = circle
  borderColor?: string;
  borderWidth?: number; // px or mm
  photoShape?: 'rectangle' | 'rounded' | 'circle';
  photoFit?: 'cover' | 'contain' | 'fill';
  overflowStrategy?: 'wrap' | 'scale_down' | 'ellipsis' | 'warning';
}

export interface TemplateSideLayout {
  fields: TemplateField[];
  backgroundColor: string;
  backgroundUrl?: string | null;
  backgroundFit?: 'fill' | 'fit' | 'crop';
  headerSvg?: string | null;
  footerSvg?: string | null;
  headerGradientColors?: [string, string] | null;
  footerGradientColors?: [string, string] | null;
}

export type TemplateFieldCategory = 'student_input' | 'student_asset' | 'auto_generated' | 'static';

export interface TemplateFieldSchemaItem {
  key: string;
  label: string;
  type: 'text' | 'photo' | 'date' | 'select';
  required: boolean;
  category: TemplateFieldCategory;
  modelKey: keyof IdCardPerson | 'student_photo';
  description?: string;
  side?: 'front' | 'back' | 'both';
}

export interface TemplateFieldSchema {
  items: TemplateFieldSchemaItem[];
  studentInputFields: TemplateFieldSchemaItem[];
  assetFields: TemplateFieldSchemaItem[];
  autoGeneratedFields: TemplateFieldSchemaItem[];
  staticFields: TemplateFieldSchemaItem[];
}

export interface TemplateLayout {
  fields: TemplateField[]; // Front side fields
  backgroundColor: string;
  backgroundUrl?: string | null; // Front background image
  backgroundFit?: 'fill' | 'fit' | 'crop';
  schoolLogoUrl?: string | null; // School / Organization logo URL
  headerSvg?: string | null; // SVG markup for header decoration
  footerSvg?: string | null; // SVG markup for footer decoration
  headerGradientColors?: [string, string] | null; // [primary, accent]
  footerGradientColors?: [string, string] | null; // [primary, accent]
  presetId?: string; // identifier for the base preset
  isDoubleSided?: boolean;
  templateType?: 'single' | 'double';
  back?: TemplateSideLayout; // Back side layout
  fieldSchema?: TemplateFieldSchemaItem[]; // Extracted dynamic field schema
}

export interface IdCardTemplate {
  id: string;
  project_id: string | null;
  name: string;
  layout: TemplateLayout;
  card_width_mm: number;
  card_height_mm: number;
  background_url: string | null;
  logo_url?: string | null;
  created_by: string;
  created_at: string;
  updated_at: string;
}

export type GenerationStatus = 'PENDING' | 'SUCCESS' | 'FAILED';

export interface IdCardGeneration {
  id: string;
  project_id: string;
  person_id: string;
  template_id: string;
  status: GenerationStatus;
  file_url: string | null;
  error_message: string | null;
  generated_by: string;
  created_at: string;
  printed_at: string | null;
}

export type AppErrorCode =
  | 'AUTH_REQUIRED'
  | 'ACCESS_DENIED'
  | 'VALIDATION_ERROR'
  | 'NOT_FOUND'
  | 'DATABASE_ERROR'
  | 'STORAGE_ERROR'
  | 'NETWORK_ERROR'
  | 'UNKNOWN_ERROR';

export class AppError extends Error {
  code: AppErrorCode;
  cause?: unknown;

  constructor(code: AppErrorCode, message: string, cause?: unknown) {
    super(message);
    this.code = code;
    this.cause = cause;
  }
}

export interface CsvValidationRow {
  rowNumber: number;
  data: Partial<IdCardPerson>;
  errors: string[];
  valid: boolean;
}

export interface PaginatedResult<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
}
